### ISSUE TITLE
/usr/lib/rsyslog/lmnsd_gtls.so packaged twice

### ISSUE THREAD

**Issue by mfournier** [rsyslog/rsyslog-pkg-debian#4]
`/usr/lib/rsyslog/lmnsd_gtls.so` is present both in rsyslog.deb and rsyslog-gnutls.deb. This leads to an uninstallable rsyslog-gnutls package:

```
$ apt-cache policy rsyslog
rsyslog:
  Installed: 8.8.0.ad1-2
  Candidate: 8.8.0.ad1-2
  Package pin: 8.8.0.ad1-2
  Version table:
 *** 8.8.0.ad1-2 1100
        500 http://debian.adiscon.com/v8-stable/ wheezy/ Packages
        100 /var/lib/dpkg/status
     5.8.11-3+deb7u2 1100
        500 http://security.debian.org/ wheezy/updates/main amd64 Packages
        500 http://mirror.switch.ch/ftp/mirror/debian/ wheezy/main amd64 Packages

$ sudo apt-get install rsyslog-gnutls 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  gnutls-bin
The following NEW packages will be installed:
  rsyslog-gnutls
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/161 kB of archives.
After this operation, 232 kB of additional disk space will be used.
(Reading database ... 60937 files and directories currently installed.)
Unpacking rsyslog-gnutls (from .../rsyslog-gnutls_8.8.0.ad1-2_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/rsyslog-gnutls_8.8.0.ad1-2_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/rsyslog/lmnsd_gtls.so', which is also in package rsyslog 8.8.0.ad1-2
Errors were encountered while processing:
 /var/cache/apt/archives/rsyslog-gnutls_8.8.0.ad1-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rgerhards** [comment]
I don't know how to fix this, but I know that it should **not** be in rsyslog.deb ;)

**Comment by mfournier** [comment]
I think that simply removing this line should do the trick:

https://github.com/rsyslog/rsyslog-pkg-debian/blob/master/rsyslog/wheezy/v8-stable/debian/rsyslog.install#L32

(it duplicates this one: https://github.com/rsyslog/rsyslog-pkg-debian/blob/master/rsyslog/wheezy/v8-stable/debian/rsyslog-gnutls.install)

... but I don't have the whole build environement setup to test my assumption.

**Comment by tt-jeremye** [comment]
I just hit this as well. It's possible to work around this with `apt-get install -o Dpkg::Options::="--force-overwrite" rsyslog-gnutls` if installing by hand, but it breaks `apt-get upgrade`.

@alorbach @friedl: any chance you could try a build with @mfournier's change? It looks plausible but I can't get your build environment working locally.

**Comment by rgerhards** [comment]
@alorbach @friedl did we correct this?

**Comment by tt-jeremye** [comment]
I noticed that 8.17 will be released today but haven't seen a Debian package yet. Would really appreciate it if 8.17's official package fixes this problem.

**Comment by friedl** [comment]
Will be fixed in future package update.

**Comment by rgerhards** [comment]
Do you still have plans to support packages for Debian as well? I am asking because of https://github.com/rsyslog/rsyslog-pkg-debian/issues/5. IMHO this was something we had discontinued (I may be wrong).

**Comment by friedl** [comment]
Discontinued for now. But I did this fix, because it was nothing big to change and so it is available in the future.

**Comment by rgerhards** [comment]
understood
