### ISSUE TITLE
Debian package for Jessie

### ISSUE THREAD

**Issue by hdep** [rsyslog/rsyslog-pkg-debian#5]
Hello,

I see that the provided package on rsyslog's website : http://www.rsyslog.com/debian-repository/ 
is only working Debian Wheezy.

Is there any plan to release a package for Debian Jessie ? This would be great.

Best regards,

**Comment by mattjay** [comment]
+1
I get an installation error on Jessie if I try to use this package.
```
vagrant@Debian-jessie-amd64-netboot:~$ sudo apt-get install rsyslog
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rsyslog : Depends: libgcrypt11 (>= 1.4.5) but it is not installable
           Depends: libgnutls26 (>= 2.12.17-0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by davidelang** [comment]
On Tue, 1 Dec 2015, Matt Johansen wrote:

> rsyslog : Depends: libgcrypt11 (>= 1.4.5) but it is not installable
>           Depends: libgnutls26 (>= 2.12.17-0) but it is not installable

what versions of these packages are available in Jessie? If they aren't 
available, is there a replacement?

David Lang

**Comment by hdep** [comment]
According to my server :
libgcrypt11 doesn't exist, but there is libgcrypt11-dev/stable 1.5.4-3+really1.6.3-2 
Seems that you should use libgcrypt20 instead.

For gnutls26 it has been upgraded to gnutls28.
There is few package, I don't know which one you exactly need : 

libgnutls-deb0-28/stable 3.3.8-6+deb8u3 amd64 [upgradable from: 3.3.8-6+deb8u2]
  bibliothÃ¨que GNU TLS - bibliothÃ¨que d'exÃ©cution principale

libgnutls-openssl27/stable 3.3.8-6+deb8u3 amd64 [upgradable from: 3.3.8-6+deb8u2]
  bibliothÃ¨que GNU TLS - enveloppe OpenSSL

libgnutls28-dbg/stable 3.3.8-6+deb8u3 amd64
  GNU TLS library - debugger symbols

libgnutls28-dev/stable 3.3.8-6+deb8u3 amd64
  GNU TLS library - development files

libgnutlsxx28/stable 3.3.8-6+deb8u3 amd64
  GNU TLS library - C++ runtime library

**Comment by Whissi** [comment]
I am also interested in recent rsyslog packages for Debian Stable aka Debian Jessie.

**Comment by mbiebl** [comment]
I could provide backports of 8.16.0 if wanted

**Comment by mbiebl** [comment]
via debian-backports, i.e.

**Comment by Whissi** [comment]
That would be great!

**Comment by iflowfor8hours** [comment]
I'm also interested in a backports package of rsyslog 8.16.0 on jessie, willing to help if I can.

**Comment by mbiebl** [comment]
I've asked to maintainer of liblognorm to provide a jessie backport for 1.1.2. Once that's available I'll be working on the jessie backport. The jessie backport won't have the czmq plugin, as czmq is not available in jessie.

**Comment by iflowfor8hours** [comment]
Great, thanks a bunch. Let me know if I can help.

---
Matt Urbanski | iflowfor8hours.info

Please use this address to reply to, and update your contact info for me
to matt@iflowfor8hours.info.


On Thu, Feb 18, 2016, at 04:40 PM, Michael Biebl wrote:
> I've asked to maintainer of liblognorm to provide a jessie backport
> for 1.1.2. Once that's available I'll be working on the jessie
> backport. The jessie backport won't have the czmq plugin, as czmq is
> not available in jessie.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/rsyslog/rsyslog-pkg-debian/issues/5#issuecomment-185994979

**Comment by hdep** [comment]
Hello,

do you have any update for this ?

regards,

**Comment by mbiebl** [comment]
There won't be any newer backports for jessie then 8.23.0-2~bpo8+1

If you need more recent versions, please consider upgrading to stretch.

**Comment by rgerhards** [comment]
Once again, I really appreciate the great work @mbiebl is doing. I just wonder as the requests for newer rsyslog on older debian seems to come up regularly if someone would be willing to do the necessary work? We (rsyslog project) could provide necessary infrastructure and can help maintain things once they are rolling, but we are most probably not great in doing great packages.

If we have volunteers, please let me know and we'll see how to get this rolling!

**Comment by teadur** [comment]
[Debian Wheezy](https://www.debian.org/releases/wheezy/) will be EOL in May 2018.
It would make sense to try to support Debian Stretch asap, sadly i don't have much experience in Debian packaging to help out. 

Debian seems to be [packaging 8.32 ](https://tracker.debian.org/pkg/rsyslog) and most likely this could be used as basis for the packages.

**Comment by hdep** [comment]
If I understand correctly jessie will not be supported because of dependency issue.

If this is right I will close this ticket then.

**Comment by hdep** [comment]
I close this ticket as nothing will be done here.
