### ISSUE TITLE
libfastjson broken

### ISSUE THREAD

**Issue by splitice** [rsyslog/rsyslog-pkg-debian#6]
the new libfastjson installs at /usr/lib/libfastjson.so.4.0.0 whereas rsyslog is compiled expecting /usr/lib/libfastjson.so.3.0.0

Resulting error:

```
rsyslogd: error while loading shared libraries: libfastjson.so.3: cannot open shared object file: No such file or directory
```

**Comment by mdthorpe** [comment]
Not directly related but probably is going to have some pretty serious impact. This is happening in using the "stable" Ubuntu repo packages as well. https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable

**Comment by davidelang** [comment]
I had a similar problem a couple months ago and it turned out that I wasn't 
compiling rsyslog against the new libfastjson.

David Lang

**Comment by scottgeary** [comment]
On Ubuntu Trusty using `rsyslog 8.19.0`:

Working: `0.99.2-0adiscon1trusty1`, which installs as `libfastjson.so.3`
Not Working `0.99.3-0adiscon1trusty1`, which installs as `libfastjson.so.4`

The `v8-stable-testing`, (currently), has the older `libfastjson 0.99.2-0` that you can install temporarily.

See
https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable-testing

Unsure how long it'll last for in there though.

**Comment by splitice** [comment]
rsyslog is built using this repository though isnt it?

https://github.com/rsyslog/rsyslog-pkg-debian/tree/master/libfastjson

I am not on Ubuntu I am on Debian. I'd rather not mess with a different compilation targets too much.

Currently I hackishly manually moved the library from an older server onto the new, and symlinked it up (I am aware this is barely better than the proposed solution).

**Comment by davidelang** [comment]
On Mon, 11 Jul 2016, Mathew Heard wrote:

> rsyslog is built using this repository though isnt it?
>
> https://github.com/rsyslog/rsyslog-pkg-debian/tree/master/libfastjson

that's not the libfastjson code, that's the debian compile instructions

here is the code

https://github.com/rsyslog/libfastjson

the next release of rsyslog will be built with the new release of libfastjson 
(0.99.3) but the current packages that are up were built with 0.99.2

David Lang

**Comment by scottgeary** [comment]
Looks like `libfastjson` `v0.99.2` was put back into the v8-stable PPA on 2016-07-12. https://launchpad.net/~adiscon/+archive/ubuntu/v8-stable

So should all be good, but may have to specifically downgrade if it's already installed 0.99.3.

**Comment by splitice** [comment]
Can confirm this does solve the problem for new installs, an explicit uninstall of the lib & re-install fixes anything in a broken state.

**Comment by allspark** [comment]
Hi, its broken again, i think only for precise (12.04)

**Comment by rgerhards** [comment]
Which error message do you get?

Sent from phone, thus brief.

Am 02.08.2016 09:22 schrieb "allspark" <notifications@github.com>:

**Comment by allspark** [comment]
i think it was this one "rsyslogd: error while loading shared libraries: libfastjson.so.3: cannot open shared object file: No such file or directory"

**Comment by rgerhards** [comment]
Thanks. I am working on getting it online with the new versions, and it looks like I had no success in regard to libfastjson. You can use the v8-devel PPA in the mean time. I'll post when the problems are considered resolved.

**Comment by rgerhards** [comment]
@allspark I *think* I have finally fixed the rsyslog packaging (right now trusty only). I would appreciate if you could give the v8-stable repo a try. Note that there might still be some startup issues due to apparmor defs, this is next on the list (see https://github.com/rsyslog/rsyslog-pkg-ubuntu/issues/48 ). Just want to get the baseline installable...

And now that I write this, I notice that this bug is for the debian package. Sorry, I am not yet working on this, it is later on the todo list :-( I know the Ubuntu definitions will work, but I need to find out more about our debian build process, so this will take some time).

**Comment by splitice** [comment]
Sorry I never did get back to you, but at some point you did fix the debian package.

Unfortunately it has regressed :(

**Comment by Hybrid512** [comment]
+1
On Debian Wheezy, apt-get dist-upgrade today and got this : 

Setting up rsyslog (8.22.0-1) ...
[ ok ] Stopping enhanced syslogd: rsyslogd already stopped.
[....] Starting enhanced syslogd: rsyslogd/usr/sbin/rsyslogd: error while loading shared libraries: libfastjson.so.3: cannot open shared object file: No such file or directory

**Comment by rgerhards** [comment]
@friedl can you please test and see where the issue is? Looks like some control file is not correctly set up.

**Comment by friedl** [comment]
Dependencies fixed. Newest version should now install correctly again with current rsyslog package 8.26.0-2.

**Comment by splitice** [comment]
Nope not fixed at all. Same issue with version 8.26.0-2

**Comment by friedl** [comment]
Have you tried it with a new Debian installation as well? I just tried it with a fresh VM and the installation works just fine. 

Can you also please try update libfastjson manually before updating rsyslog? The current packaged version is 0.99.5.

We also just updated the packages for the new release, which now has a fixed dependency for the current libfastjson release, so it should update correctly automatically.

**Comment by Hybrid512** [comment]
This issue keeps regressing again and again ... Debian wheezy stable repository, Rsyslog 8.27.0-1 and it crashes asking for libfastjson.so.3 while libfastjson 0.99.5-1 provides libfastjson.so.4
